import type { Metadata } from 'next';
import '@/app/globals.css';
import { Kumbh_Sans } from 'next/font/google';
import Navigation from './ui/Navigation';
import Provider from './lib/provider/Provider';
const kumbh = Kumbh_Sans({
	weight: ['400', '700'],
	style: ['normal'],
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={kumbh.className}>
				<Provider>
					<div className="container mx-auto max-w-[1200px] ">
						<Navigation />
						<div className="">{children}</div>
					</div>
				</Provider>
			</body>
		</html>
	);
}
